name: Commits
on:
  push:
    branches: '!master'
jobs:
  build:
    name: Build and Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'oracle'
          java-version: '22'
          cache: 'maven'
      - name: Maven Test
        run: mvn test
